version: '3'

services:
  postgres:
    container_name: 'fastfeet_postgres'
    image: 'postgres:11'
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - 'fastpgdata:/var/lib/postgresql/data/'

  redis:
    container_name: fastfeet_redis
    image: 'redis:alpine'
    command: redis-server --requirepass ${REDIS_ROOT_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - 'fastredisdata:/data'

  mongo:
    container_name: go_mongo
    image: 'mongo'
    env_file: .env
    command: 'mongod --auth --storageEngine wiredTiger'
    ports:
      - '27017:27017'
    volumes:
      - 'fastmongodata:/data/db'

volumes:
  fastpgdata:
  fastredisdata:
  fastmongodata:
